apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sports-store-app-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sports-store.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: sports-store-app-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        mongodb-root-password: "{{ `{{ .mongoRootPassword }}` }}"
        mongodb-replica-set-key: "{{ `{{ .mongoReplicaSetKey }}` }}"
        JWT_SECRET: "{{ `{{ .jwtSecretKey }}` }}"
        MONGO_URI: "mongodb://root:{{ `{{ .mongoRootPassword | urlquery }}` }}@{{ include "sports-store.mongoHost" . }}:27017/?authSource=admin&replicaSet={{ .Values.mongodb.replicaSetName }}"
  data:
    - secretKey: mongoRootPassword
      remoteRef:
        key: sports-store/production/config
        property: MONGO_INITDB_ROOT_PASSWORD
    - secretKey: jwtSecretKey
      remoteRef:
        key: sports-store/production/config
        property: JWT_SECRET_KEY
    - secretKey: mongoReplicaSetKey
      remoteRef:
        key: sports-store/production/config
        property: MONGODB_REPLICA_SET_KEY
