apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sports-store-redis-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sports-store.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: sports-store-redis-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        redis-password: "{{ `{{ .redisPassword }}` }}"
  data:
    - secretKey: redisPassword
      remoteRef:
        key: sports-store/production/config
        property: REDIS_PASSWORD
