apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  labels:
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: sports-store
spec:
  project: sports-store-project
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.41.1
    helm:
      releaseName: argo-rollouts
      values: |
        installCRDs: true
        keepCRDs: true
        clusterInstall: true

        controller:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi

        dashboard:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
