apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8sgpt-resources
  namespace: argocd
  labels:
    app.kubernetes.io/name: k8sgpt-resources
    app.kubernetes.io/part-of: sports-store
spec:
  project: default
  source:
    repoURL: https://github.com/Deploy-On-Friday2-0/sports-store-deployments.git
    targetRevision: k8sgpt/free-tier-quota
    path: apps/k8sgpt
  destination:
    server: https://kubernetes.default.svc
    namespace: k8sgpt-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
