apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: sports-store
spec:
  project: default
  source:
    repoURL: https://github.com/Deploy-On-Friday2-0/sports-store-deployments.git
    targetRevision: main
    path: apps/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
